package CapaPresentacion;

import CapaComun.Cm_ClsComboItem;
import CapaComun.Cm_ClsPais;
import CapaNegocio.Ng_ClsCliente;
import CapaNegocio.Ng_ClsPais;
import java.util.*;
import java.util.regex.*;
import javax.swing.JOptionPane;

//@author Dennis David

public class JFRegistroCliente extends javax.swing.JFrame {

    Ng_ClsCliente ng_cliente;
    Ng_ClsPais ng_pais;
    List<Cm_ClsPais> listaPais;
    private Pattern patNombre = Pattern.compile("[a-zA-ZñáéíóúÑÁÉÍÓÚ\\s]{1,25}");
    private Pattern patPasaporte = Pattern.compile("[0-9]{10}");
    private Pattern patContrasenia = Pattern.compile("^(?=.*[0-9])(?=.*[a-zñáéíóú])(?=.*[A-ZÑÁÉÍÓÚ]).{6,64}$");

    public JFRegistroCliente() {
        initComponents();
        ng_cliente = new Ng_ClsCliente();
        ng_pais = new Ng_ClsPais();
        listaPais = ng_pais.mostrarPaisAll(jCBPais, false, 0);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFNombreRegistroCliente = new javax.swing.JTextField();
        jTFApellidoRegistroCliente = new javax.swing.JTextField();
        jTFCedulaRegistroCliente = new javax.swing.JTextField();
        jPFContraseniaCliente = new javax.swing.JPasswordField();
        jCBPais = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLMaximo1 = new javax.swing.JLabel();
        jLMaximo2 = new javax.swing.JLabel();
        jLFormatoContrasenia = new javax.swing.JLabel("<html>La contraseña debe tener de 6 a 64 caracteres y contener una combinación de caracteres en mayúscula, minúscula y números.</html>");
        jBRegistrarCliente = new javax.swing.JButton();
        jBCancelarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Pasaporte:");

        jLabel4.setText("País:");

        jLabel6.setText("Contraseña:");

        jTFNombreRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreRegistroClienteActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.jpg"))); // NOI18N

        jLMaximo1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLMaximo1.setText("Máximo 25 caracteres");

        jLMaximo2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLMaximo2.setText("Máximo 25 caracteres");

        jLFormatoContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLFormatoContrasenia.setText("<html>La contraseña debe tener de 6 a 64 caracteres y contener una combinación de caracteres en mayúscula, minúscula y números.</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFormatoContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLMaximo1)
                            .addComponent(jLMaximo2)
                            .addComponent(jTFNombreRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jTFApellidoRegistroCliente)
                            .addComponent(jTFCedulaRegistroCliente)
                            .addComponent(jPFContraseniaCliente))))
                .addGap(468, 468, 468))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombreRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMaximo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApellidoRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMaximo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCedulaRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFContraseniaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFormatoContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBRegistrarCliente.setText("Registrar");
        jBRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarClienteActionPerformed(evt);
            }
        });

        jBCancelarCliente.setText("Cancelar");
        jBCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jBRegistrarCliente)
                .addGap(36, 36, 36)
                .addComponent(jBCancelarCliente)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrarCliente)
                    .addComponent(jBCancelarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreRegistroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreRegistroClienteActionPerformed

    private void jBRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarClienteActionPerformed
        Matcher matNombre = this.patNombre.matcher(this.jTFNombreRegistroCliente.getText());
        Matcher matApellido = this.patNombre.matcher(this.jTFApellidoRegistroCliente.getText());
        Matcher matPasaporte = this.patPasaporte.matcher(this.jTFCedulaRegistroCliente.getText());
        Matcher matContrasenia = this.patContrasenia.matcher(this.jPFContraseniaCliente.getText());
        if(matNombre.matches() && matApellido.matches() && matPasaporte.matches() && matContrasenia.matches() && this.jCBPais.getSelectedIndex() != 0){
            Object item = jCBPais.getSelectedItem();
            String value = ((Cm_ClsComboItem) item).getValue();
            System.out.println("value es: " + value);

            int respuesta = ng_cliente.insertarCliente(jTFNombreRegistroCliente.getText(),
                    jTFApellidoRegistroCliente.getText(), jTFCedulaRegistroCliente.getText(),
                    jPFContraseniaCliente.getText(),Integer.parseInt(value));

            if (respuesta >= 1) {
                JOptionPane.showMessageDialog(null, "Registro realizado con éxito");
                    limpiarCamposRegistro();
                    dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrió un error.\nVerifique la información e inténtelo nuevamente.\n\nSi el problema persiste, comuníquese inmediatamente con los estudiantes.");
            }
        }else{
            String error = "";
            error += matNombre.matches()?"":"- El nombre ingresado no es válido.\n";
            error += matApellido.matches()?"":"- El apellido ingresado no es válido.\n";
            error += matPasaporte.matches()?"":"- El número de pasaporte ingresado no es válido.\n";
            error += matContrasenia.matches()?"":"- La contraseña ingresada no es válida. La contraseña debe tener de 6 a 64 caracteres y contener una combinación de caracteres en mayúscula, minúscula y números.\n";
            error += this.jCBPais.getSelectedIndex() != 0?"":"- No ha seleccionado un país.\n";
            JOptionPane.showMessageDialog(null, "Comprueba la siguiente información:\n\n" + error, "Error en el registro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBRegistrarClienteActionPerformed

    public void limpiarCamposRegistro(){
        jTFApellidoRegistroCliente.setText("");
        jTFCedulaRegistroCliente.setText("");
        jTFNombreRegistroCliente.setText("");
        jPFContraseniaCliente.setText("");
        jCBPais.setSelectedIndex(0);
    }
    private void jBCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarClienteActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarCliente;
    private javax.swing.JButton jBRegistrarCliente;
    private javax.swing.JComboBox<String> jCBPais;
    private javax.swing.JLabel jLFormatoContrasenia;
    private javax.swing.JLabel jLMaximo1;
    private javax.swing.JLabel jLMaximo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPFContraseniaCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFApellidoRegistroCliente;
    private javax.swing.JTextField jTFCedulaRegistroCliente;
    private javax.swing.JTextField jTFNombreRegistroCliente;
    // End of variables declaration//GEN-END:variables
}
