SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VUELO] (
		[ID_VUELO]          [varchar](10) COLLATE Modern_Spanish_CI_AS NOT NULL,
		[RUTA]              [varchar](120) COLLATE Modern_Spanish_CI_AS NULL,
		[ESTADODEVUELO]     [bit] NULL,
		CONSTRAINT [PK_VUELO]
		PRIMARY KEY
		NONCLUSTERED
		([ID_VUELO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[VUELO] SET (LOCK_ESCALATION = TABLE)
GO
