SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RESERVA] (
		[ID_RESERVA]     [int] NOT NULL,
		[PASAPORTE]      [bigint] NOT NULL,
		[ID_VUELO]       [varchar](10) COLLATE Modern_Spanish_CI_AS NOT NULL,
		[ID_ASIENTO]     [int] NOT NULL,
		CONSTRAINT [PK_RESERVA]
		PRIMARY KEY
		NONCLUSTERED
		([ID_RESERVA])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[RESERVA]
	WITH CHECK
	ADD CONSTRAINT [FK_RESERVA_CONTIENE_VUELO]
	FOREIGN KEY ([ID_VUELO]) REFERENCES [dbo].[VUELO] ([ID_VUELO])
ALTER TABLE [dbo].[RESERVA]
	CHECK CONSTRAINT [FK_RESERVA_CONTIENE_VUELO]

GO
ALTER TABLE [dbo].[RESERVA]
	WITH CHECK
	ADD CONSTRAINT [FK_RESERVA_ESTA2_ASIENTO]
	FOREIGN KEY ([ID_ASIENTO]) REFERENCES [dbo].[ASIENTO] ([ID_ASIENTO])
ALTER TABLE [dbo].[RESERVA]
	CHECK CONSTRAINT [FK_RESERVA_ESTA2_ASIENTO]

GO
ALTER TABLE [dbo].[RESERVA]
	WITH CHECK
	ADD CONSTRAINT [FK_RESERVA_TIENE2_CLIENTE]
	FOREIGN KEY ([PASAPORTE]) REFERENCES [dbo].[CLIENTE] ([PASAPORTE])
ALTER TABLE [dbo].[RESERVA]
	CHECK CONSTRAINT [FK_RESERVA_TIENE2_CLIENTE]

GO
CREATE NONCLUSTERED INDEX [TIENE_FK]
	ON [dbo].[RESERVA] ([PASAPORTE])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EXISTEN_FK]
	ON [dbo].[RESERVA] ([ID_ASIENTO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CONTIENE_FK]
	ON [dbo].[RESERVA] ([ID_VUELO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVA] SET (LOCK_ESCALATION = TABLE)
GO
