SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ASIENTO] (
		[ID_ASIENTO]     [int] NOT NULL,
		[TIPO]           [int] NOT NULL,
		[NUMERO]         [char](60) COLLATE Modern_Spanish_CI_AS NOT NULL,
		[UBICACION]      [varchar](60) COLLATE Modern_Spanish_CI_AS NOT NULL,
		[ESTADO]         [bit] NOT NULL,
		CONSTRAINT [PK_ASIENTO]
		PRIMARY KEY
		NONCLUSTERED
		([ID_ASIENTO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[ASIENTO]
	WITH CHECK
	ADD CONSTRAINT [FK_ASIENTO_CUENTA_CLASE]
	FOREIGN KEY ([TIPO]) REFERENCES [dbo].[CLASE] ([TIPO])
ALTER TABLE [dbo].[ASIENTO]
	CHECK CONSTRAINT [FK_ASIENTO_CUENTA_CLASE]

GO
CREATE NONCLUSTERED INDEX [CUENTA_FK]
	ON [dbo].[ASIENTO] ([TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASIENTO] SET (LOCK_ESCALATION = TABLE)
GO
