SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLASE] (
		[TIPO]            [int] NOT NULL,
		[NOMBRECLASE]     [varchar](59) COLLATE Modern_Spanish_CI_AS NOT NULL,
		CONSTRAINT [PK_CLASE]
		PRIMARY KEY
		NONCLUSTERED
		([TIPO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[CLASE] SET (LOCK_ESCALATION = TABLE)
GO
