SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENTE] (
		[PASAPORTE]         [bigint] NOT NULL,
		[PAIS]              [varchar](12) COLLATE Modern_Spanish_CI_AS NOT NULL,
		[NOMBR_CLIENTE]     [varchar](70) COLLATE Modern_Spanish_CI_AS NULL,
		CONSTRAINT [PK_CLIENTE]
		PRIMARY KEY
		NONCLUSTERED
		([PASAPORTE])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[CLIENTE] SET (LOCK_ESCALATION = TABLE)
GO
